import { useCallback, useEffect, useState } from "react";
import Button from "../components/Button.jsx";
import DriverModal from "../components/drivers/DriverModal.jsx";
import StatusBadge from "../components/StatusBadge.jsx";
import { changeDriverStatus, createDriver, listAssignableVehicles, listDrivers, removeDriver, subscribeToDrivers, updateDriver } from "../services/driverService.js";
import TablePage from "./TablePage.jsx";
export default function Drivers(){
 const[drivers,setDrivers]=useState([]),[vehicles,setVehicles]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[modalError,setModalError]=useState(""),[modal,setModal]=useState(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const[driverRows,vehicleRows]=await Promise.all([listDrivers(),listAssignableVehicles()]);setDrivers(driverRows);setVehicles(vehicleRows)}catch(e){setError(e.message||"Unable to retrieve drivers.")}finally{setLoading(false)}},[]);
 useEffect(()=>{load();return subscribeToDrivers(load)},[load]);
 const save=async values=>{setBusy(true);setModalError("");try{if(modal.mode==="edit")await updateDriver(modal.driver.id,values);else await createDriver(values);setModal(null);await load()}catch(e){setModalError(e.message||"Unable to save this driver.")}finally{setBusy(false)}};
 const deactivate=async()=>{if(!window.confirm(`Set ${modal.driver.name} to Inactive? The driver will remain in trip history.`))return;setBusy(true);setModalError("");try{await changeDriverStatus(modal.driver.id,"Inactive");setModal(null);await load()}catch(e){setModalError(e.message||"Unable to update this driver.")}finally{setBusy(false)}};
 const remove=async()=>{if(!window.confirm(`Permanently remove ${modal.driver.name}? Use Inactive instead if this driver has operational history.`))return;setBusy(true);setModalError("");try{await removeDriver(modal.driver.id);setModal(null);await load()}catch(e){setModalError(e.message||"Unable to remove this driver.")}finally{setBusy(false)}};
 const columns=[{key:"name",header:"Driver",render:row=><div className="device-name-cell"><strong>{row.name}</strong><span>{row.licenseNumber}</span></div>},{key:"status",header:"Status",render:row=><StatusBadge status={row.status}/>},{key:"assignedVehicle",header:"Assigned Vehicle"},{key:"contactNumber",header:"Contact Number"},{key:"createdAt",header:"Added",render:row=>row.createdAt?new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(row.createdAt)):"Not recorded"}];
 return <><TablePage eyebrow="Fleet Operations" title="Drivers" description="Manage driver credentials, availability, contact details, and vehicle assignments." searchPlaceholder="Search driver, license, contact, vehicle, or status…" rows={drivers} columns={columns} filterKeys={["name","licenseNumber","contactNumber","assignedVehicle","status"]} loading={loading} error={error} onRetry={load} actions={<Button onClick={()=>{setModalError("");setModal({mode:"create",driver:null})}}>Add driver</Button>} onRowClick={driver=>{setModalError("");setModal({mode:"view",driver})}} rowLabel={driver=>`View details for ${driver.name}`} emptyTitle="No drivers registered" emptyDescription="Add the first driver to begin assigning fleet operations."/>{modal&&<DriverModal mode={modal.mode} driver={modal.driver} vehicles={vehicles} busy={busy} error={modalError} onClose={()=>setModal(null)} onSave={save} onEdit={()=>setModal(current=>({...current,mode:"edit"}))} onDeactivate={deactivate} onRemove={remove}/>}</>
}
