import { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import Button from "../components/Button.jsx";
import Input from "../components/Input.jsx";
import { useAuth } from "../context/AuthContext.jsx";
import { APPEARANCE_KEY, DEFAULT_APPEARANCE, loadPreference, saveAppearance } from "../preferences.js";
import { APP_DESCRIPTION } from "../theme.js";
import novaFleetLogo from "../assets/novafleet-logo.png";

export default function Login() {
  const navigate = useNavigate(); const location = useLocation(); const { signIn } = useAuth();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const [appearance, setAppearance] = useState(() => loadPreference(APPEARANCE_KEY, DEFAULT_APPEARANCE));
  const changeTheme = (theme) => { const next = { ...appearance, theme }; setAppearance(next); saveAppearance(next); };
  const handleLogin = async (event) => { event.preventDefault(); if (loading) return; setError(""); setLoading(true); try { await signIn({ email, password }); navigate(location.state?.from || "/dashboard", { replace: true }); } catch (err) { setError(err.message || "Unable to sign in."); } finally { setLoading(false); } };
  return <div className="login-page"><div className="portal-appearance-switch" aria-label="Portal appearance">{[{ theme: "light", icon: "&#9788;", label: "Light mode" }, { theme: "dark", icon: "&#9680;", label: "Dark mode" }].map((option) => <button type="button" className={appearance.theme === option.theme ? "active" : ""} key={option.theme} onClick={() => changeTheme(option.theme)} aria-label={option.label} title={option.label}><span aria-hidden="true" dangerouslySetInnerHTML={{ __html: option.icon }} /></button>)}</div><section className="login-brand"><div className="login-brand-content"><img className="logo-mark" src={novaFleetLogo} alt="NovaFleet" /><h1 className="login-title">NovaFleet</h1><p className="login-copy">{APP_DESCRIPTION}</p></div></section><section className="login-form"><h2 className="login-heading">Welcome back</h2><p className="login-subtitle">Sign in with your authorized fleet operations account.</p><form className="grid" style={{ gap: 20 }} onSubmit={handleLogin} noValidate><Input id="email" label="Work email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="name@organization.com" autoComplete="email" required disabled={loading} /><label className="input-wrap password-input-wrap" htmlFor="password"><span className="input-label">Password</span><span className="password-input-control"><input id="password" className="input" type={showPassword ? "text" : "password"} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Enter your password" autoComplete="current-password" required disabled={loading} /><button type="button" className="password-toggle-button" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? "Hide password" : "Show password"} title={showPassword ? "Hide password" : "Show password"} disabled={loading}>{showPassword ? "Hide" : "Show"}</button></span></label><Button type="submit" disabled={loading} aria-busy={loading}>{loading ? "Verifying account..." : "Sign in securely"}</Button></form><p className="login-security-note">Your access level is assigned by your NovaFleet administrator.</p>{error && <div className="login-error" role="alert" aria-live="assertive">{error}</div>}</section></div>;
}