import { useCallback, useEffect, useState } from "react";
import Button from "../components/Button.jsx";
import MaintenanceModal from "../components/maintenance/MaintenanceModal.jsx";
import StatusBadge from "../components/StatusBadge.jsx";
import { createMaintenanceRecord, listMaintenanceRecords, listMaintenanceVehicles, removeMaintenanceRecord, subscribeToMaintenance, updateMaintenanceRecord } from "../services/maintenanceService.js";
import TablePage from "./TablePage.jsx";
export default function Maintenance(){
 const[records,setRecords]=useState([]),[vehicles,setVehicles]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[modalError,setModalError]=useState(""),[modal,setModal]=useState(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const[recordRows,vehicleRows]=await Promise.all([listMaintenanceRecords(),listMaintenanceVehicles()]);setRecords(recordRows);setVehicles(vehicleRows)}catch(e){setError(e.message||"Unable to retrieve maintenance records.")}finally{setLoading(false)}},[]);
 useEffect(()=>{load();return subscribeToMaintenance(load)},[load]);
 const save=async values=>{setBusy(true);setModalError("");try{if(modal.mode==="edit")await updateMaintenanceRecord(modal.record.id,values);else await createMaintenanceRecord(values);setModal(null);await load()}catch(e){setModalError(e.message||"Unable to save this maintenance record.")}finally{setBusy(false)}};
 const remove=async()=>{if(!window.confirm(`Remove the ${modal.record.maintenanceType} record for ${modal.record.vehicle}? This action cannot be undone.`))return;setBusy(true);setModalError("");try{await removeMaintenanceRecord(modal.record.id);setModal(null);await load()}catch(e){setModalError(e.message||"Unable to remove this maintenance record.")}finally{setBusy(false)}};
 const columns=[{key:"vehicle",header:"Vehicle",render:row=><div className="device-name-cell"><strong>{row.vehicle}</strong><span>{row.vehicleModel}</span></div>},{key:"scheduleStatus",header:"Status",render:row=><StatusBadge status={row.scheduleStatus}/>},{key:"maintenanceType",header:"Service"},{key:"serviceDate",header:"Service Date"},{key:"cost",header:"Cost"},{key:"notes",header:"Notes",render:row=><span className="maintenance-notes-cell">{row.notes||"No notes"}</span>}];
 return <><TablePage eyebrow="Management" title="Maintenance" description="Schedule upcoming service and maintain an accurate vehicle service history." searchPlaceholder="Search vehicle, service, status, date, or notes…" rows={records} columns={columns} filterKeys={["vehicle","vehicleModel","scheduleStatus","maintenanceType","serviceDate","notes"]} loading={loading} error={error} onRetry={load} actions={<Button onClick={()=>{setModalError("");setModal({mode:"create",record:null})}}>Schedule maintenance</Button>} onRowClick={record=>{setModalError("");setModal({mode:"view",record})}} rowLabel={record=>`View ${record.maintenanceType} record for ${record.vehicle}`} emptyTitle="No maintenance records" emptyDescription="Schedule the first service record for a fleet vehicle."/>{modal&&<MaintenanceModal mode={modal.mode} record={modal.record} vehicles={vehicles} busy={busy} error={modalError} onClose={()=>setModal(null)} onSave={save} onEdit={()=>setModal(current=>({...current,mode:"edit"}))} onRemove={remove}/>}</>
}
