import { supabase } from "./supabase.js";

const DEVICE_SELECT = `id,device_uid,device_name,device_type,serial_number,firmware_version,connection_status,gps_status,last_seen_at,installed_at,notes,vehicle_id,latitude,longitude,location_updated_at,vehicles:vehicle_id(id,plate_number,model)`;
const mapDevice = (row) => { const vehicle = Array.isArray(row.vehicles) ? row.vehicles[0] : row.vehicles; return { id: row.id, deviceUid: row.device_uid, name: row.device_name, type: row.device_type, serialNumber: row.serial_number || "...", firmwareVersion: row.firmware_version || "...", connectionStatus: row.connection_status, gpsStatus: row.gps_status, lastSeenAt: row.last_seen_at, installedAt: row.installed_at, notes: row.notes || "", vehicleId: row.vehicle_id || "", latitude: row.latitude ?? "", longitude: row.longitude ?? "", locationUpdatedAt: row.location_updated_at || "", assignedVehicle: vehicle?.plate_number || "Unassigned", vehicleModel: vehicle?.model || "" }; };
const toPayload = (v) => ({ device_uid:v.deviceUid.trim(), device_name:v.name.trim(), device_type:v.type, serial_number:v.serialNumber.trim()||null, firmware_version:v.firmwareVersion.trim()||null, connection_status:v.connectionStatus, gps_status:v.gpsStatus, installed_at:v.installedAt||null, vehicle_id:v.vehicleId||null, latitude:v.latitude===""?null:Number(v.latitude), longitude:v.longitude===""?null:Number(v.longitude), location_updated_at:v.latitude!==""&&v.longitude!==""?new Date().toISOString():null, notes:v.notes.trim()||null });
function check(error) { if (!error) return; if (error.code === "42P01") throw new Error("The fleet.iot_devices table is not installed yet. Run the included Supabase migration first."); if (error.code === "23505") throw new Error("That device ID or serial number is already registered."); throw error; }
export async function getDevices(){const{data,error}=await supabase.from("iot_devices").select(DEVICE_SELECT).order("created_at",{ascending:false});check(error);return(data||[]).map(mapDevice)}
export async function getDeviceVehicles(){const{data,error}=await supabase.from("vehicles").select("id,plate_number,model").order("plate_number");check(error);return data||[]}
export async function createDevice(values){const{data,error}=await supabase.from("iot_devices").insert(toPayload(values)).select(DEVICE_SELECT).single();check(error);return mapDevice(data)}
export async function updateDevice(id,values){const{data,error}=await supabase.from("iot_devices").update(toPayload(values)).eq("id",id).select(DEVICE_SELECT).single();check(error);return mapDevice(data)}
export async function removeDevice(id){const{error}=await supabase.from("iot_devices").delete().eq("id",id);check(error)}
export function subscribeToDevices(onChange){const channel=supabase.channel("admin-iot-devices").on("postgres_changes",{event:"*",schema:"fleet",table:"iot_devices"},onChange).subscribe();return()=>supabase.removeChannel(channel)}
