import { supabase } from "./supabase.js";
const DRIVER_SELECT="id,profile_id,full_name,license_number,contact_number,status,created_at,vehicles!vehicles_assigned_driver_id_fkey(id,plate_number,model,status)";
const titleCase=(value,fallback="Inactive")=>value?String(value).replace(/[_-]+/g," ").replace(/\b\w/g,l=>l.toUpperCase()):fallback;
function mapDriver(row){const vehicle=row.vehicles?.[0];return{id:row.id,profileId:row.profile_id||"",name:row.full_name,licenseNumber:row.license_number||"Not recorded",contactNumber:row.contact_number||"Not recorded",status:titleCase(row.status),assignedVehicleId:vehicle?.id||"",assignedVehicle:vehicle?.plate_number||"Unassigned",vehicleModel:vehicle?.model||"",createdAt:row.created_at}}
function check(error){if(!error)return;if(error.code==="23505")throw new Error("That license number is already registered.");if(error.code==="23503")throw new Error("This driver has related trip or fleet records and cannot be removed. Set the driver to Inactive instead.");throw error}
async function assignVehicle(driverId,vehicleId){const clear=await supabase.from("vehicles").update({assigned_driver_id:null}).eq("assigned_driver_id",driverId);check(clear.error);if(vehicleId){const set=await supabase.from("vehicles").update({assigned_driver_id:driverId}).eq("id",vehicleId);check(set.error)}}
export async function listDrivers(){const{data,error}=await supabase.from("drivers").select(DRIVER_SELECT).order("full_name");check(error);return(data||[]).map(mapDriver)}
export async function listAssignableVehicles(){const{data,error}=await supabase.from("vehicles").select("id,plate_number,model,status,assigned_driver_id").order("plate_number");check(error);return data||[]}
export async function createDriver(values){const{data,error}=await supabase.from("drivers").insert({full_name:values.name.trim(),license_number:values.licenseNumber.trim()||null,contact_number:values.contactNumber.trim()||null,status:values.status.toLowerCase()}).select("id").single();check(error);await assignVehicle(data.id,values.assignedVehicleId);return data.id}
export async function updateDriver(id,values){const{error}=await supabase.from("drivers").update({full_name:values.name.trim(),license_number:values.licenseNumber.trim()||null,contact_number:values.contactNumber.trim()||null,status:values.status.toLowerCase()}).eq("id",id);check(error);await assignVehicle(id,values.assignedVehicleId)}
export async function changeDriverStatus(id,status){const{error}=await supabase.from("drivers").update({status:status.toLowerCase()}).eq("id",id);check(error)}
export async function removeDriver(id){const [trips,baseline]=await Promise.all([supabase.from("trips").select("id",{count:"exact",head:true}).eq("driver_id",id),supabase.from("driver_baseline").select("id",{count:"exact",head:true}).eq("driver_id",id)]);check(trips.error);check(baseline.error);if((trips.count||0)>0||(baseline.count||0)>0)throw new Error("This driver has operational history and cannot be removed. Set the driver to Inactive instead.");await assignVehicle(id,"");const{error}=await supabase.from("drivers").delete().eq("id",id);check(error)}
export function subscribeToDrivers(onChange){const driverChannel=supabase.channel("admin-drivers").on("postgres_changes",{event:"*",schema:"fleet",table:"drivers"},onChange).subscribe();const vehicleChannel=supabase.channel("admin-driver-assignments").on("postgres_changes",{event:"*",schema:"fleet",table:"vehicles"},onChange).subscribe();return()=>{supabase.removeChannel(driverChannel);supabase.removeChannel(vehicleChannel)}}

