-- NovaFleet: row-level security posture + persistent change auditing.
-- Ported from the ad-hoc SQL that previously lived in client/supabase/ so the
-- behavior is versioned. Idempotent: safe to re-run.
--
-- Architecture note: data access now goes through the Express REST API using the
-- Supabase service-role key, which bypasses RLS. RLS is kept enabled as
-- defense-in-depth so a leaked anon/publishable key cannot read fleet data
-- directly. Only public.profiles is readable by the authenticated browser
-- session (needed for the login/role bootstrap and admin user list).

begin;

-- ---------------------------------------------------------------------------
-- Administrator detection helper (SECURITY DEFINER avoids RLS recursion).
-- ---------------------------------------------------------------------------
create or replace function public.is_novafleet_administrator()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid())
      and lower(role) in ('admin', 'administrator')
  );
$$;
revoke all on function public.is_novafleet_administrator() from public;
grant execute on function public.is_novafleet_administrator() to authenticated;

-- ---------------------------------------------------------------------------
-- public.profiles: a user sees their own profile; admins see all.
-- ---------------------------------------------------------------------------
alter table public.profiles enable row level security;
grant select on table public.profiles to authenticated;
drop policy if exists "Administrators can view all profiles" on public.profiles;
create policy "Administrators can view all profiles"
on public.profiles for select to authenticated
using (id = (select auth.uid()) or (select public.is_novafleet_administrator()));

-- ---------------------------------------------------------------------------
-- Enable RLS on every fleet data table. No authenticated data policies are
-- added: the Express service role bypasses RLS; the browser must not read
-- these tables directly.
-- ---------------------------------------------------------------------------
do $$
declare
  target text;
begin
  foreach target in array array[
    'vehicles', 'drivers', 'trips', 'sensor_readings', 'incident_alerts',
    'risk_scores', 'route_anomalies', 'maintenance_records', 'fuel_logs',
    'driver_baseline', 'iot_devices'
  ]
  loop
    if to_regclass(format('fleet.%I', target)) is not null then
      execute format('alter table fleet.%I enable row level security', target);
    end if;
  end loop;
end
$$;

-- ---------------------------------------------------------------------------
-- Persistent change auditing.
-- ---------------------------------------------------------------------------
create table if not exists fleet.audit_logs (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_id uuid references auth.users (id) on delete set null,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  schema_name text not null,
  table_name text not null,
  record_id text,
  old_data jsonb,
  new_data jsonb
);
create index if not exists audit_logs_occurred_at_idx on fleet.audit_logs (occurred_at desc);
create index if not exists audit_logs_actor_id_idx on fleet.audit_logs (actor_id);
create index if not exists audit_logs_resource_idx on fleet.audit_logs (schema_name, table_name, record_id);

alter table fleet.audit_logs enable row level security;
drop policy if exists "Administrators can view audit logs" on fleet.audit_logs;
create policy "Administrators can view audit logs"
on fleet.audit_logs for select to authenticated
using ((select public.is_novafleet_administrator()));

create or replace function fleet.capture_audit_change()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, fleet
as $$
declare
  before_row jsonb;
  after_row jsonb;
  changed_record_id text;
begin
  if TG_OP = 'INSERT' then
    before_row := null;
    after_row := to_jsonb(NEW);
  elsif TG_OP = 'UPDATE' then
    before_row := to_jsonb(OLD);
    after_row := to_jsonb(NEW);
    if before_row = after_row then
      return NEW;
    end if;
  else
    before_row := to_jsonb(OLD);
    after_row := null;
  end if;

  changed_record_id := coalesce(after_row ->> 'id', before_row ->> 'id');

  insert into fleet.audit_logs (actor_id, action, schema_name, table_name, record_id, old_data, new_data)
  values (auth.uid(), TG_OP, TG_TABLE_SCHEMA, TG_TABLE_NAME, changed_record_id, before_row, after_row);

  return coalesce(NEW, OLD);
end;
$$;

-- Attach the audit trigger to every mutable NovaFleet table that exists.
do $$
declare
  target record;
begin
  for target in
    select * from (values
      ('public', 'profiles'), ('fleet', 'vehicles'), ('fleet', 'drivers'),
      ('fleet', 'trips'), ('fleet', 'iot_devices'), ('fleet', 'sensor_readings'),
      ('fleet', 'incident_alerts'), ('fleet', 'maintenance_records'),
      ('fleet', 'fuel_logs'), ('fleet', 'risk_scores'), ('fleet', 'route_anomalies'),
      ('fleet', 'driver_baseline')
    ) as tracked(schema_name, table_name)
  loop
    if to_regclass(format('%I.%I', target.schema_name, target.table_name)) is not null then
      execute format('drop trigger if exists novafleet_audit_change on %I.%I', target.schema_name, target.table_name);
      execute format(
        'create trigger novafleet_audit_change after insert or update or delete on %I.%I for each row execute function fleet.capture_audit_change()',
        target.schema_name, target.table_name
      );
    end if;
  end loop;
end
$$;

commit;
