-- NovaFleet: administrator user visibility and persistent change auditing
-- Run once in Supabase SQL Editor.

begin;

-- Administrators can view every application profile, including dispatcher accounts.
-- Use a SECURITY DEFINER role check so the profiles policy never queries itself.
create or replace function public.is_novafleet_administrator()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and lower(role) in ('admin', 'administrator')
  );
$$;

revoke all on function public.is_novafleet_administrator() from public;
grant execute on function public.is_novafleet_administrator() to authenticated;


drop policy if exists "Administrators can view all profiles" on public.profiles;
create policy "Administrators can view all profiles"
on public.profiles
for select
to authenticated
using (
  id = (select auth.uid())
  or (select public.is_novafleet_administrator())
);

create table if not exists fleet.audit_logs (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_id uuid null references auth.users(id) on delete set null,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  schema_name text not null,
  table_name text not null,
  record_id text,
  old_data jsonb,
  new_data jsonb
);

create index if not exists audit_logs_occurred_at_idx
  on fleet.audit_logs (occurred_at desc);
create index if not exists audit_logs_actor_id_idx
  on fleet.audit_logs (actor_id);
create index if not exists audit_logs_resource_idx
  on fleet.audit_logs (schema_name, table_name, record_id);

alter table fleet.audit_logs enable row level security;

drop policy if exists "Administrators can view audit logs" on fleet.audit_logs;
create policy "Administrators can view audit logs"
on fleet.audit_logs
for select
to authenticated
using ((select public.is_novafleet_administrator()));

grant usage on schema fleet to authenticated;
grant select on fleet.audit_logs to authenticated;

create or replace function fleet.capture_audit_change()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, fleet
as $$
declare
  before_row jsonb;
  after_row jsonb;
  changed_record_id text;
begin
  if TG_OP = 'INSERT' then
    before_row := null;
    after_row := to_jsonb(NEW);
  elsif TG_OP = 'UPDATE' then
    before_row := to_jsonb(OLD);
    after_row := to_jsonb(NEW);

    -- Do not store updates that did not actually alter persisted values.
    if before_row = after_row then
      return NEW;
    end if;
  else
    before_row := to_jsonb(OLD);
    after_row := null;
  end if;

  changed_record_id := coalesce(after_row ->> 'id', before_row ->> 'id');

  insert into fleet.audit_logs (
    actor_id,
    action,
    schema_name,
    table_name,
    record_id,
    old_data,
    new_data
  )
  values (
    auth.uid(),
    TG_OP,
    TG_TABLE_SCHEMA,
    TG_TABLE_NAME,
    changed_record_id,
    before_row,
    after_row
  );

  return coalesce(NEW, OLD);
end;
$$;

-- Add the same lightweight audit trigger to every mutable NovaFleet table.
do $$
declare
  target record;
begin
  for target in
    select *
    from (values
      ('public', 'profiles'),
      ('fleet', 'vehicles'),
      ('fleet', 'drivers'),
      ('fleet', 'trips'),
      ('fleet', 'iot_devices'),
      ('fleet', 'sensor_readings'),
      ('fleet', 'incident_alerts'),
      ('fleet', 'maintenance_records'),
      ('fleet', 'fuel_logs'),
      ('fleet', 'risk_scores'),
      ('fleet', 'route_anomalies'),
      ('fleet', 'driver_baseline')
    ) as tracked(schema_name, table_name)
  loop
    if to_regclass(format('%I.%I', target.schema_name, target.table_name)) is not null then
      execute format(
        'drop trigger if exists novafleet_audit_change on %I.%I',
        target.schema_name,
        target.table_name
      );
      execute format(
        'create trigger novafleet_audit_change after insert or update or delete on %I.%I for each row execute function fleet.capture_audit_change()',
        target.schema_name,
        target.table_name
      );
    end if;
  end loop;
end
$$;

commit;
